FROM registry.git.hk.asiaticketing.com/technology/system/deploy/ansible:latest

RUN wget https://releases.hashicorp.com/terraform/0.12.18/terraform_0.12.18_linux_amd64.zip | unzip -d /usr/local/bin/

WORKDIR /deploy
COPY . ./terraform_repo
