version: '3'

services:
  ets-terraform:
    build:
      dockerfile: Dockerfile
      context: .
    volumes:
      - .:/deploy/terraform_repo/
      - ~/.aws:/root/.aws
    env_file:
      - .env.unittest
    environment:
      CI_PROJECT_DIR: /build
    command: 'terraform init -backend-config=".env.unittest.tfvars"'