FROM registry.git.hk.asiaticketing.com/technology/system/deploy/ansible:latest

RUN aws configure
RUN wget -O /tmp/terraform.zip https://releases.hashicorp.com/terraform/0.12.18/terraform_0.12.18_linux_amd64.zip && sudo unzip /tmp/terraform.zip -d /usr/local/bin/

WORKDIR /deploy
COPY . ./terraform_repo

USER deploy
RUN chown -R deploy:deploy /deploy
